# Generated by Django 5.0.3 on 2024-10-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_innovaSoft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacion',
            name='idCuenta',
        ),
        migrations.CreateModel(
            name='SubCuenta',
            fields=[
                ('idSubCuenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigoCuenta', models.CharField(max_length=256, unique=True)),
                ('nombre', models.CharField(max_length=256, unique=True)),
                ('idDeMayor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_innovaSoft.cuentademayor')),
            ],
            options={
                'db_table': 'subCuenta',
                'ordering': ['idSubCuenta'],
            },
        ),
        migrations.CreateModel(
            name='CuentaDetalle',
            fields=[
                ('idCuentaDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('codigoCuenta', models.CharField(max_length=256, unique=True)),
                ('nombre', models.CharField(max_length=256, unique=True)),
                ('idCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_innovaSoft.subcuenta')),
            ],
            options={
                'db_table': 'cuentaDetalle',
                'ordering': ['idCuentaDetalle'],
            },
        ),
        migrations.AddField(
            model_name='transacion',
            name='idSubCuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App_innovaSoft.subcuenta'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
