# Generated by Django 5.0.3 on 2024-10-27 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_innovaSoft', '0002_remove_transacion_idcuenta_subcuenta_cuentadetalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacion',
            name='idCuentaDetalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_innovaSoft.cuentadetalle'),
        ),
    ]
