# Generated by Django 5.0.3 on 2024-10-30 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_innovaSoft', '0004_alter_cuentadetalle_idcuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='libromayor',
            name='idRegistroCuentaT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App_innovaSoft.registrocuentat'),
            preserve_default=False,
        ),
    ]
