# Generated by Django 5.0.3 on 2024-10-30 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_innovaSoft', '0005_libromayor_idregistrocuentat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacion',
            name='idSubCuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_innovaSoft.subcuenta'),
        ),
    ]
