# Generated by Django 5.0.3 on 2024-10-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_innovaSoft', '0006_alter_transacion_idsubcuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocuentat',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
