# Generated by Django 5.0.3 on 2024-10-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_innovaSoft', '0007_registrocuentat_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('idPeriodo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicioDePeriodo', models.DateField()),
                ('fechaFinDePeriodo', models.DateField()),
            ],
            options={
                'db_table': 'periodoContable',
                'ordering': ['idPeriodo'],
            },
        ),
        migrations.DeleteModel(
            name='LibroMayor',
        ),
    ]
