# Generated by Django 5.0.3 on 2024-11-02 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_innovaSoft', '0008_periodocontable_delete_libromayor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('idSubCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_innovaSoft.subcuenta')),
            ],
        ),
    ]
