# Generated by Django 5.0.3 on 2024-11-04 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_innovaSoft', '0008_periodocontable_delete_libromayor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='materiaPrima',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestaciones',
            name='recargoPorVacaciones',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='prestaciones',
            name='tasaAFP',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='prestaciones',
            name='tasaIncaf',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='prestaciones',
            name='tasaSeguro',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('idSubCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_innovaSoft.subcuenta')),
            ],
        ),
    ]
